timezone: America/Sao_Paulo
encoding: UTF-8

plugins:
    - jekyll-sitemap

sass:
    style: compressed

exclude:
    - Dockerfile.dev
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - stack-dev.yml
